name: Deploy Test

on:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy
        runs-on: [ubuntu-latest]
        steps:

            - name: Checkout
              uses: actions/checkout@v3.3.0

            - name: Install Modules
              shell: pwsh
              run: |
                Install-Module Az.Resources

            - name: deploy ARM
              shell: pwsh
              run: |
                New-AzResourceGroupDeployment -ResourceGroupName "epac-testing" -TemplateFile .\deploy.json
